# Generated by Django 3.0.5 on 2020-04-25 11:24

from django.db import migrations, models
import django.utils.timezone
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=32, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=32, verbose_name='Прізвище')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Приєднався')),
                ('role', models.CharField(choices=[('A', 'Адміністратор'), ('S', 'Студент'), ('M', 'Ментор'), ('E', 'Роботодавець')], default='S', max_length=1, verbose_name='Роль')),
                ('city', models.CharField(max_length=64, verbose_name='Місто')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компанія або навчальний заклад')),
                ('scope', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сфера діяльності або факультет')),
                ('course', models.PositiveIntegerField(null=True, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
            managers=[
                ('objects', web.models.ProfileManager()),
            ],
        ),
    ]
