# Generated by Django 3.0.5 on 2020-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
    ]
