# Generated by Django 3.0.5 on 2020-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('I', 'Стажування'), ('F', 'Волонтерство'), ('P', 'Платний курс')], default='I', max_length=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
    ]
