# Generated by Django 3.0.5 on 2020-04-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200425_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
