# Generated by Django 3.0.5 on 2020-04-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200425_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='students', to='web.Opportunity', verbose_name='Підписки'),
        ),
    ]
